spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commentdb
    username: root
    password: Odyssey@123

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 8082